CREATE TABLE MEMMANAGE 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, AGE NUMBER(*, 0) NOT NULL 
, GENDER VARCHAR2(20 BYTE) NOT NULL 
, NUM VARCHAR2(20 BYTE) NOT NULL 
, ADDRESS VARCHAR2(50 BYTE) NOT NULL 
, INFO VARCHAR2(50 BYTE) 
)